### ISSUE TITLE
Error on executing vagrant up

### ISSUE THREAD

**Issue by djnet00** [terion-name/Lagrant#2]
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
- Shared folder that have NFS enabled do no support owner/group
  attributes. Host path: ./

**Comment by terion-name** [comment]
Strange... What is your host OS?

**Comment by djnet00** [comment]
Hello, is Mac OS 10.9.2

**Comment by terion-name** [comment]
Hello
@djnet00 looks like you have no NFSD installed or it is disabled
Take a look at this manual: https://developer.apple.com/library/mac/documentation/darwin/reference/manpages/man8/nfsd.8.html
Check this please
